language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
script: npm run generate
deploy:
  provider: surge
  project: ./dist/
  domain: https://perudo-calculator.surge.sh
  skip_cleanup: true
